### ISSUE TITLE
How to train VITAEv2 with MAE

### ISSUE THREAD

**Issue by yunh-w** [ViTAE-Transformer/ViTAE-Transformer#1]
Can you tell me how to train VITAEv2 with MAE ?  The VITAEv2  is a hierarchical backbone but the VIT used in MAE is a plain-backbone. I don't know how to train VITAEv2 with MAE.

**Comment by Annbless** [comment]
Hi, 

Thanks for your interest! Please refer to Sec 3.3 and Sec 4.4.1 in the [ViTAEv2](https://arxiv.org/pdf/2202.10108.pdf) paper. We use MAE to train the isotropic design of ViTAE. How to use MAE to train the hierarchical version backbone is an iinteresting topic, and we leave it for our future research.

**Comment by yunh-w** [comment]
@Annbless I see the ViTAEv2 is a hierarchical backbone. How to pre-train a plain ViTAE backbone and fine-tune to hierarchical ViTAEv2..

**Comment by RogerZhangzz** [comment]
Hi,
The MAE pretrained ViTAE is not a stage-wise hierarchical backbone. And we pretrain stage-wise ViTAEv2 using the full supervision from ImageNet-22k in our paper. Please refer to Sec 3.3 and Sec 4.4.1 for details.
Hoping this can address your question.
Thank you.

**Comment by seefun** [comment]
Will the ImageNet-22k and MAE pretrained ViTAE backbone model be open source? @Annbless

**Comment by Annbless** [comment]
> Will the ImageNet-22k and MAE pretrained ViTAE backbone model be open source? @Annbless

Yes The ViTAE-B model pretraiend with MAE and finetuned with ImageNet-22k has been released in [link](https://github.com/ViTAE-Transformer/ViTAE-Transformer/tree/main/Image-Classification#models-with-imagenet-22k-pretraining). We will upload other weights as soon as possible.

**Comment by RogerZhangzz** [comment]
> Will the ImageNet-22k and MAE pretrained ViTAE backbone model be open source? @Annbless

Hi. The ImageNet-22k pretrained ViTAEv2_B, as well as other backbones and training logs, has been released. Please refer to the relevant part in [README.md](https://github.com/ViTAE-Transformer/ViTAE-Transformer/tree/main/Image-Classification#readme).

**Comment by seefun** [comment]
> > Will the ImageNet-22k and MAE pretrained ViTAE backbone model be open source? @Annbless
> 
> Hi. The ImageNet-22k pretrained ViTAEv2_B, as well as other backbones and training logs, has been released. Please refer to the relevant part in [README.md](https://github.com/ViTAE-Transformer/ViTAE-Transformer/tree/main/Image-Classification#readme).

Thanks！
