### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by chengjunfengmaster** [ViTAE-Transformer/ViTAE-Transformer#3]
hi ,do you have the pretrained weights?

**Comment by Annbless** [comment]
Hi, 

The pretrained weights can be fought in [link](https://github.com/ViTAE-Transformer/ViTAE-Transformer/tree/main/Image-Classification#main-results-on-imagenet-1k-with-pretrained-models).

**Comment by RogerZhangzz** [comment]
Hi. The ImageNet-22k pretrained ViTAEv2_B, as well as other backbone variants and training logs, has been released. Please refer to the relevant part in [README.md](https://github.com/ViTAE-Transformer/ViTAE-Transformer/tree/main/Image-Classification#readme).
