### ISSUE TITLE
Performance about ViTAEv2-S

### ISSUE THREAD

**Issue by zhangzjn** [ViTAE-Transformer/ViTAE-Transformer#5]
I used the default experimental setting of Swin to train VitAEV2-S. It took 3 days for a single 8*V100, and the result was 81.926, which was smaller than the official 82.6. Could you please provide me the difference between the experimental settings of ViTAEV2-S and Swin? And when will the training script be released? thank you

**Comment by RogerZhangzz** [comment]
Hi, Thank you for your interest.

The training scrips, training logs and weight of ViTAEv2 variants have been released. Please refer to [README.md](https://github.com/ViTAE-Transformer/ViTAE-Transformer/tree/main/Image-Classification#readme) for more details.
