### ISSUE TITLE
EMA results from the log-ViTAEv2_B

### ISSUE THREAD

**Issue by zhangzjn** [ViTAE-Transformer/ViTAE-Transformer#8]
Thanks for the good job! But according to the log, the result of the ViTAEv2_B in the paper seems to use EMA that is not seen in the paper. This may lead to potentially unfair comparisons?

![image](https://user-images.githubusercontent.com/26211183/170054099-1f675bd9-7a53-45f0-b396-0f28079e9d0d.png)

**Comment by Annbless** [comment]
Hi, thanks for your attention.

It is a common practice to use EMA in the ImageNet-1K fully supervised learning for vision transformers, as demonstrated in DeiT, T2T-ViT, ConvNeXt, and our ViTAE.
